const { discoverWebsites: discoverOpenStreetMap } = require("./prospectDiscovery");
const WEBS_DOCS_URL = "https://directory.websdocs.com/api/directory";
const PROVIDER_ORDER = ["openstreetmap", "websdocs"];
const DEFAULT_QUERIES = [
  ["auto repair shops","Pretoria"],["electricians","Pretoria"],["security companies","Pretoria"],["accountants","Pretoria"],["property businesses","Pretoria"],["guesthouses","Pretoria"],["salons","Pretoria"],
  ["auto repair shops","Centurion"],["electricians","Centurion"],["security companies","Centurion"],["accountants","Centurion"],["property businesses","Centurion"],["guesthouses","Centurion"],["salons","Centurion"]
].map(([label,city])=>({label,city}));
function providerQueries(date=new Date()){const count=Math.max(1,Math.min(Number(process.env.AUTOMATION_DISCOVERY_QUERY_COUNT||2),4));const start=Math.floor(date.getTime()/86400000)%DEFAULT_QUERIES.length;return Array.from({length:count},(_,i)=>DEFAULT_QUERIES[(start+i)%DEFAULT_QUERIES.length]);}
function hostOf(value){try{return new URL(value).hostname.toLowerCase().replace(/^www\./,"");}catch{return "";}}
function extractWebsDocsCandidates(payload,query){const rows=Array.isArray(payload?.results)?payload.results:Array.isArray(payload?.listings)?payload.listings:Array.isArray(payload?.items)?payload.items:[];const seen=new Set();return rows.map(row=>{const website=row?.website||row?.websiteUrl||row?.url||row?.domain||"";const normalized=hostOf(website);if(!normalized||seen.has(normalized))return null;seen.add(normalized);return{website,normalized,name:String(row?.name||row?.businessName||"").trim()||null,city:query.city,category:query.label};}).filter(Boolean);}
async function discoverWebsDocs({queries=providerQueries(),maxCandidates=20,fetchImpl=fetch}={}){const candidates=[],seen=new Set(),queryResults=[];const limit=Math.max(1,Math.min(Number(maxCandidates)||20,40));for(const query of queries){if(candidates.length>=limit)break;const params=new URLSearchParams({q:query.label,country:"ZA",city:query.city,limit:String(Math.min(20,limit-candidates.length))});const response=await fetchImpl(WEBS_DOCS_URL+"?"+params.toString(),{method:"GET",headers:{Accept:"application/json","User-Agent":"Site Rescue Studio Prospect Discovery/1.0"}});let payload=null;try{payload=await response.json();}catch{}if(!response.ok){const error=new Error(payload?.message||`WebsDocs discovery returned HTTP ${response.status}.`);error.status=response.status;throw error;}const found=extractWebsDocsCandidates(payload,query);let added=0;for(const candidate of found){if(seen.has(candidate.normalized))continue;seen.add(candidate.normalized);candidates.push(candidate);added++;if(candidates.length>=limit)break;}queryResults.push({query:query.label,city:query.city,websiteCandidatesAdded:added});}return{source:"websdocs",candidates,queries:queryResults,candidateCount:candidates.length};}
async function discoverWithProviders({maxCandidates=20,queries=providerQueries(),isProviderAvailable=async()=>true,recordSuccess=async()=>{},recordFailure=async()=>{}}={}){const errors=[];for(const provider of PROVIDER_ORDER){if(!(await isProviderAvailable(provider)))continue;try{const result=provider==="openstreetmap"?await discoverOpenStreetMap({maxCandidates}):await discoverWebsDocs({maxCandidates,queries});await recordSuccess(provider);return{...result,provider,failoverUsed:provider!==PROVIDER_ORDER[0],errors};}catch(error){errors.push({provider,message:String(error?.message||error),status:error?.status||null});await recordFailure(provider,error);}}const error=new Error("All configured discovery providers are unavailable.");error.providerErrors=errors;throw error;}
module.exports={WEBS_DOCS_URL,PROVIDER_ORDER,DEFAULT_QUERIES,providerQueries,extractWebsDocsCandidates,discoverWebsDocs,discoverWithProviders};